baseURL = "http://cdf-hugo.s3-website-eu-west-1.amazonaws.com/"
languageCode = 'en-us'
title = 'Hugo AWS S3 CD'
theme= "ananke"
[[deployment.targets]]
# An arbitray name for this target.
name = "awsbucket"
URL = "s3://cdf-hugo?region=eu-west-1"